version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/node:10
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json"}}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm Install
      - save_cache:
          paths:
            - node_modules
          keys: v1-dependencies-{{ checksum "package.json"}}
      - run:
          name: Run tests
          command: npm test
      - store_test_result:
          path: test-results
workflows:
  version: 2
  build_test:
    jobs:
      - build_and_test
